### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by SaraVieira** [kkemple/hwyd#3]
https://www.skcript.com/svr/firebase-social-login-with-react-native/

**Comment by kkemple** [comment]
this is resolved by #2

**Comment by kkemple** [comment]
oh, social! nevermind, re-opening 😂

**Comment by SaraVieira** [comment]
Imma take this on ! Wish me luck!

**Comment by SaraVieira** [comment]
DUUUUUDE IT WORKED

https://kapture-mtdqilnsxh.now.sh

**Comment by kkemple** [comment]
wuuuut!! that was so fast, you and firebase === 🚀
