### ISSUE TITLE
[Tab bar] icons padding; [Report] title font stylin

### ISSUE THREAD

**Issue by rdela** [kkemple/hwyd#4]
Like the design, looks fancy, chill, and restrained at the same time!

Maybe more spacing/padding above the icons in bottom tab bar? Also talked about title for no reports should look like journal message too, could try and do both maybe? How would you feel about a PR for this?

Relevant links
https://reactnavigation.org/docs/tab-based-navigation.html
https://developer.android.com/training/implementing-navigation/lateral.html
https://developer.apple.com/documentation/uikit/uitabbarcontroller
(**EDIT:** fixed dupe iOS link for intended Android counterpart)

iPhone X screenshot:
![nothing-to-report-yeti](https://user-images.githubusercontent.com/74381/37547327-3cf009f6-292e-11e8-98ca-7f9a7520fe21.jpg)

**Comment by SaraVieira** [comment]
Both thoae would be great by me, watchu thing @kkemple?

Also let us know if you need any help

**Comment by kkemple** [comment]
agreed! would love a PR for this! Time to get all-contributors set up on this repo!! 🎉 🙌
